[package]
name = "trip-night-instruction"
version = "0.1.0"
edition = "2021"
description = "Instruction set implementation of Trip Night emulator, a CHIP-8 virtual machine in Rust"

[dependencies]
trip-night-core = { path = "../trip-night-core", version = "0.1.0" }
